# Generated by Django 3.2 on 2021-04-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='exam_lo',
            field=models.FileField(upload_to=''),
        ),
    ]
