# Generated by Django 3.2 on 2021-04-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competition_exam_lo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='exam_lo',
            field=models.FileField(upload_to='exam_los'),
        ),
    ]
